repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-vcs-permalinks
      - id: mixed-line-ending
        args:
          - --fix=lf
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        exclude: ^examples/custom_converters/elu_converter/setup.py
  - repo: https://github.com/pre-commit/mirrors-clang-format
    rev: v14.0.6
    hooks:
      - id: clang-format
        types_or: [c++, c, cuda]
  - repo: https://github.com/keith/pre-commit-buildifier
    rev: 5.1.0
    hooks:
    -   id: buildifier
        args:
          - --warnings=all
    -   id: buildifier-lint